# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Franco Marchesoni
# Description of the Site
description: Learning to share 
# URL of Image of the Site
# site-image: https://pbs.twimg.com/profile_images/1296616176081133569/0AVFLYJz_400x400.jpg
site-image: https://pbs.twimg.com/media/FDOUuKbWQAcmUkb?format=jpg&name=4096x4096 # assets/images/me.jpg
# Keywords of the Site
site-keywords: # Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://pbs.twimg.com/profile_images/1296616176081133569/0AVFLYJz_400x400.jpg

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: chile.jpg
# https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: marchesoniacland@gmail.com
facebook_username:
twitter_username: franchesoni
instagram_username: franchesoni
linkedin_username: franco-marchesoni
github_username: franchesoni
youtube_channel_id: #UCk_93NXYP-U_AOB5GfWlOow
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
# google-analytics: UA-163806439-1
google-analytics: G-45FMJZ2XJC

# Disqus
disqus-shortname: 

# Name of the Author
author-name: franchesoni
# URL for the Image of the Author
author-image: https://pbs.twimg.com/media/FDOUuKbWQAcmUkb?format=jpg&name=4096x4096 # assets/images/me.jpg # https://pbs.twimg.com/profile_images/1296616176081133569/0AVFLYJz_400x400.jpg  # https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: "
  The meaning of life is there where the question does not arise.
  I am kidding, this was just a phrase to test the webpage.
  Me? I am an AI enthusiast, but I like ideas in general.
  I am trying to figure out what to do, how and why.
  In the meantime I am learning everything from everyone.
  "
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://franchesoni.github.io/webpage/  # https://github.com/franchesoni

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
